name: lumo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon/bookmark_black.png
    - assets/icon/bookmark_light.png
    - assets/icon/discount_black.png
    - assets/icon/discount_light.png
    - assets/icon/home_black.png
    - assets/icon/home_light.png
    - assets/icon/search_black.png
    - assets/icon/search_light.png
    - assets/icon/user_black.png
    - assets/icon/user_light.png
    - assets/icon/tag.png
    - assets/icon/google_icon.png
    - assets/icon/facebook_icon.png
    - assets/image/banner_one.png
    - assets/image/banner_two.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/poppins/Poppins-Regular.ttf
          weight: 400
